import {fileURLToPath} from 'node:url';
// Real Rust API regression coverage for account resume, key setup, retries and restart.
// Website/provider data and mutations are synthetic; only owned browser contexts close.
import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
process.chdir(fileURLToPath(new URL('..', import.meta.url)));
const ports=JSON.parse(await fs.readFile(process.env.HYCLI_FIXTURE_OUTPUT || '.cache/e2e-ports.json','utf8'));
const en=JSON.parse(await fs.readFile('dashboard/src/locales/en.json','utf8'));
const browser=process.env.TEST_CDP?await chromium.connectOverCDP(process.env.TEST_CDP):await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN,args:['--no-sandbox','--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();page.setDefaultTimeout(120000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const button=(parent,key)=>(key.startsWith('nav.')?parent.locator('.sidebar'):parent).getByRole('button',{name:en[key],exact:true});
const dialog=()=>page.getByRole('dialog');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const poll=async(fn,timeout=180000)=>{const until=Date.now()+timeout;while(Date.now()<until){if(await fn())return;await sleep(300);}throw Error('Lifecycle condition timed out');};
const control=async body=>{const response=await fetch(ports.website+'/fixture/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});assert.equal(response.status,200);};
const api=(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const {csrf}=await(await fetch('/api/session')).json();const response=await fetch(path,{method,headers:{'content-type':'application/json','x-hycli-csrf':csrf},body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,body:await response.json()};},{path,method,body});
const state=async()=>(await api('/api/state')).body;
const done=async(id,timeout=180000)=>{let job;await poll(async()=>{job=(await api('/api/jobs/'+id)).body;return ['completed','failed','cancelled'].includes(job.status);},timeout);return job;};
const findJob=async(kind,excluded=[])=>{let job;await poll(async()=>{job=(await state()).jobs.find(j=>j.kind===kind&&!excluded.includes(j.id));return !!job;});return job;};
const openSite=async title=>{await button(page,'nav.websites').click();await page.locator('.site-card').filter({hasText:title}).getByRole('button',{name:en['sites.openActions'],exact:true}).click();};
try {
 await page.goto(ports.dashboard+'/?launch='+ports.launch,{waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:en['sites.title'],exact:true}).waitFor();
 console.log('Account selection resumes preparation through the real route.');
 assert.equal((await api('/api/sites/library','PATCH',{title:'Lifecycle research library'})).status,200);
 await poll(async()=>await page.getByRole('button',{name:'Lifecycle research library',exact:true}).count()===1);
 let previous=(await state()).jobs.map(j=>j.id);
 await openSite('Lifecycle research library');await button(dialog(),'accounts.add').click();
 await button(dialog(),'accounts.useAccount').first().waitFor({timeout:360000});
 const resumeResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/sites/prepare'&&response.request().method()==='POST');
 await button(dialog(),'accounts.useAccount').first().click();assert.equal((await resumeResponse).status(),200);await dialog().waitFor({state:'hidden'});
 let resumed=await findJob('prepare',previous);assert.equal((await done(resumed.id,Number(process.env.HYCLI_PREPARATION_TEST_TIMEOUT_MS)||180000)).status,'completed');
 assert.equal((await state()).jobs.filter(job=>job.kind==='prepare'&&!previous.includes(job.id)).length,1);
 console.log('Atomic duplicate preparation, cancellation and retry.');
 await control({delay_ai_ms:3000});
 const started=await api('/api/sites/prepare','POST',{site_id:'library',url:ports.website,provider:'openai'});assert.equal(started.status,200);
 const duplicate=await api('/api/sites/prepare','POST',{site_id:'library',url:ports.website,provider:'openai'});assert.equal(duplicate.status,409);assert.equal(duplicate.body.error.code,'job_running');
 assert.equal((await api(`/api/jobs/${started.body.job.id}/cancel`,'POST')).status,200);assert.equal((await done(started.body.job.id)).status,'cancelled');
 await control({delay_ai_ms:0});
 console.log('Import a website with a declared API key, then save it through the UI.');
 const spec={spec_version:1,site:{name:'key-fixture',title:'Secure workspace',base_url:ports.website},auth:[{name:'website-key',kind:'header',header:'x-api-key',prefix:'',value_from:'store:key-fixture/api-key'}],operations:[{name:'find-articles',desc:'Read private references.',method:'GET',path:'/key-items',effect:'read',evidence:'Synthetic fixture API documentation',auth:'website-key'}]};
 await button(page,'nav.websites').click();await page.locator('main input[type=file]').setInputFiles({name:'secure.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(spec))});
 await poll(async()=>(await state()).sites.some(site=>site.id==='key-fixture'));
 await poll(async()=>!(await state()).jobs.some(job=>job.kind==='describe'&&job.site_id==='key-fixture'&&['queued','running'].includes(job.status)));
 await openSite('Secure workspace');
 const keyInput=dialog().getByLabel(/Website Key · API key/i);await keyInput.fill('synthetic-website-key');await button(dialog().locator('.website-keys'),'common.save').click();await dialog().getByText(en['accounts.keySaved'],{exact:true}).waitFor();await poll(async()=>await keyInput.inputValue()==='');
 assert.ok(!JSON.stringify(await state()).includes('synthetic-website-key'));
 await dialog().getByRole('button',{name:/^Find articles/}).click();await button(dialog(),'actions.run').click();await dialog().getByText('Private reference',{exact:true}).waitFor();
 let action=(await state()).jobs.find(job=>job.kind==='action'&&job.site_id==='key-fixture');assert.ok(action);
 const result=(await api(`/api/jobs/${action.id}/result`)).body;assert.ok(!JSON.stringify(result).includes('synthetic-website-key'));
 console.log('Failed summary can be retried from Activity and produces a readable result.');
 previous=(await state()).jobs.map(j=>j.id);await control({fail_summary:true});await button(dialog(),'actions.summary').click();let summary=await findJob('summary',previous);assert.equal((await done(summary.id)).status,'failed');await control({fail_summary:false});await button(dialog(),'common.close').click();
 await button(page,'nav.activity').click();let row=page.locator('.activity-item').filter({has:page.getByText(en['activity.failed'],{exact:true})}).filter({hasText:'Secure workspace'}).first();
 previous=(await state()).jobs.map(j=>j.id);await button(row,'common.retry').click();summary=await findJob('summary',previous);assert.equal((await done(summary.id)).status,'completed');assert.ok((await api(`/api/jobs/${summary.id}`)).body.result.summary);
 console.log('Key rotation clears authentication pause; removal revokes access.');
 assert.equal((await api('/api/sites/key-fixture/credentials/website-key','PUT',{key:'wrong-key'})).status,200);
 let request=await api('/api/sites/key-fixture/actions/find-articles','POST',{inputs:{},account_id:''});assert.equal((await done(request.body.job.id)).error_code,'auth_required');
 assert.equal((await api('/api/sites/key-fixture/credentials/website-key','PUT',{key:'synthetic-website-key'})).status,200);
 request=await api('/api/sites/key-fixture/actions/find-articles','POST',{inputs:{},account_id:''});assert.equal((await done(request.body.job.id)).status,'completed');
 await button(page,'nav.websites').click();await openSite('Secure workspace');
 const downloadPromise=page.waitForEvent('download');await button(dialog(),'sites.export').click();const download=await downloadPromise;const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);const exported=Buffer.concat(chunks).toString();assert.ok(exported.includes('store:key-fixture/api-key'));assert.ok(!exported.includes('synthetic-website-key'));await button(dialog(),'common.close').click();
 console.log('Server session restart reconnects without reloading the page.');
 const oldCookies=await context.cookies(ports.dashboard);await control({restart_dashboard:true});
 // The session survives a restart, so the open page keeps working without a new launch address.
 await poll(async()=>{try{return Array.isArray((await state()).sites);}catch{return false;}},45000);
 assert.equal((await context.cookies(ports.dashboard)).find(c=>c.name==='hycli_session')?.value,oldCookies.find(c=>c.name==='hycli_session')?.value);
 await openSite('Secure workspace');await dialog().getByLabel(en['sites.titleLabel'],{exact:true}).fill('Secure workspace after restart');await button(dialog().locator('.website-detail-settings'),'common.save').click();await poll(async()=>(await state()).sites.find(site=>site.id==='key-fixture')?.title==='Secure workspace after restart');await button(dialog(),'common.close').click();
 console.log('Account import/removal, agent handoff and site removal.');
 const imported=await api('/api/accounts/import','POST',{site_id:'key-fixture',url:ports.website,content:JSON.stringify([{name:'session',value:'synthetic-browser-secret',domain:'127.0.0.1',path:'/'}])});assert.equal(imported.status,200);assert.equal((await api('/api/accounts/'+imported.body.account.id,'DELETE')).status,200);assert.ok(!(await state()).accounts.some(account=>account.id===imported.body.account.id));assert.equal((await state()).sites.find(site=>site.id==='key-fixture').account_id,'');
 const handoff=(await api('/api/handoff?site=library')).body;assert.equal(handoff.config.mcpServers.hycli.env.HYCLI_DATA_DIR,ports.data);assert.ok(handoff.config.mcpServers.hycli.args.includes('--allow-local'));assert.ok(handoff.config.mcpServers.hycli.args.includes('--sites-only'));assert.ok(handoff.command.includes('HYCLI_DATA_DIR='));assert.ok(handoff.command.includes(handoff.config.mcpServers.hycli.command));
 const general=(await api('/api/handoff')).body;assert.ok(!general.config.mcpServers.hycli.args.includes('--sites-only'));assert.ok(general.instructions.includes('hycli_prepare'));assert.ok(general.instructions.includes('hycli_run'));
 await button(page,'nav.agents').click();await button(page,'agents.openSetup').click();await dialog().locator('.handoff-content').waitFor();assert.ok((await dialog().locator('.handoff-content').innerText()).includes('mcpServers'));await button(dialog(),'common.close').click();
 assert.equal((await api('/api/sites/key-fixture/credentials/website-key','DELETE')).status,200);assert.equal((await api('/api/sites/key-fixture/actions/find-articles','POST',{inputs:{},account_id:''})).status,401);
 assert.equal((await api('/api/sites/key-fixture','DELETE')).status,200);assert.ok(!(await state()).sites.some(site=>site.id==='key-fixture'));
 assert.equal((await(await fetch(ports.website+'/fixture/status')).json()).secret_prompts,0);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({lifecycle:'passed',accountResume:'real route, exactly once',preparation:'duplicate blocked; cancelled',websiteKey:'save, read, redaction, rotate, remove',summary:'failure and retry',session:'automatic reconnect after server restart',management:'import, export, account removal, site removal, MCP setup'},null,2));
}catch(error){await page.screenshot({path:'.cache/lifecycle-failure.png',fullPage:true,animations:'disabled'}).catch(()=>{});throw error;}finally{await control({fail_summary:false,delay_ai_ms:0}).catch(()=>{});await context.close();if(!process.env.TEST_CDP)await browser.close();}
if(process.env.TEST_CDP)process.exit(process.exitCode||0);
